const {chromium}=require('playwright');const fs=require('fs'),path=require('path');
const base=process.env.AEGISES_HOME_URL||'http://127.0.0.1:8875/';
const out='/tmp/aegises-home-review';fs.mkdirSync(out,{recursive:true});
const assert=(ok,msg)=>{if(!ok)throw Error(msg)};
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage({viewport:{width:1440,height:1100},colorScheme:'light'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base,{waitUntil:'networkidle'});
assert((await page.title())==='AEGISES — Intelligence with Integrity','Title');
const anchors=await page.evaluate(()=>[...document.querySelectorAll('a[href^="#"]')].map(a=>a.hash.slice(1)).filter(x=>!document.getElementById(x)));assert(!anchors.length,'Broken anchors');
const links=await page.evaluate(()=>[...new Set([...document.querySelectorAll('a[href^="/"],link[rel=stylesheet],img')].map(e=>e.getAttribute('href')||e.getAttribute('src')))]);
for(const rel of links){const r=await page.request.get(new URL(rel,base).href);assert(r.ok(),`Failed destination ${rel}`)}
const sizes=[1440,1024,768,390,320];const views=[];
for(const width of sizes){await page.setViewportSize({width,height:width<800?900:1100});await page.goto(base,{waitUntil:'networkidle'});const metrics=await page.evaluate(()=>({width:innerWidth,body:document.documentElement.scrollWidth,heading:document.querySelector('h1').innerText}));assert(metrics.body<=width,`Page overflow at ${width}: ${metrics.body}`);await page.screenshot({path:path.join(out,`home-${width}.png`),fullPage:true});views.push(metrics)}
await page.setViewportSize({width:1440,height:1100});await page.goto(base);await page.keyboard.press('Tab');assert(await page.locator('.skip-link').evaluate(el=>el===document.activeElement),'Skip link must be first keyboard target');await page.keyboard.press('Enter');assert(await page.evaluate(()=>location.hash==='#main'),'Skip link destination');await page.locator('.primary-link').click();assert(await page.evaluate(()=>location.hash==='#research'),'Research navigation');
await page.emulateMedia({reducedMotion:'reduce'});assert(await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior==='auto'),'Reduced motion');
const nojs=await browser.newPage({javaScriptEnabled:false});await nojs.goto(base);assert(await nojs.locator('.featured-paper').count()===2,'Featured research without JS');assert(await nojs.locator('.research-row').count()===4,'Technical research without JS');await nojs.close();assert(!errors.length,'Browser errors');
await page.setViewportSize({width:1200,height:630});await page.setContent('<html><head><style>body{margin:0;background:#f5f6f0;color:#15313d;font-family:Arial}main{padding:49px 63px}.brand{font-size:24px;letter-spacing:5px}.rule{border-top:1px solid #d5dfdd;margin:26px 0 43px}.kicker{font-size:12px;letter-spacing:2px;color:#087e80}h1{font:100px/1.07 Georgia;letter-spacing:-4px;margin:20px 0 26px}h1 span{color:#087e80}p{font-size:19px;color:#597078;margin:0}.footer{margin-top:37px;border-top:1px solid #d5dfdd;padding-top:21px;font-size:12px;letter-spacing:1px;color:#087e80}</style></head><body><main><div class="brand">AEGISES</div><div class="rule"></div><div class="kicker">PUBLIC RESEARCH FOR GOVERNABLE INTELLIGENCE</div><h1>Intelligence<br>with <span>integrity.</span></h1><p>Governance, autonomy and the ethical evolution of artificial intelligence.</p><div class="footer">POLICY &nbsp;&nbsp; / &nbsp;&nbsp; ACCOUNTABLE SYSTEMS &nbsp;&nbsp; / &nbsp;&nbsp; ENFORCEABLE BOUNDARIES</div></main></body></html>');await page.screenshot({path:path.resolve(__dirname,'../assets/social-preview.png')});
const report={verified_at:new Date().toISOString(),base,views,local_destinations:links.length,internal_anchors:true,keyboard_skip:true,research_navigation:true,reduced_motion:true,no_javascript_content:true,browser_errors:errors};fs.writeFileSync(path.join(__dirname,'validation.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
