"""Curated, representative instruments. This is not an exhaustive statutory census."""
from pathlib import Path
import json, csv
ROOT=Path(__file__).resolve().parents[1]
# State | name | pathway | instrument | domains | status | source type | URL | supported observation | boundary
raw='''AL|Alabama|targeted|HB172 (2024)|media|enacted|mixed|https://alison.legislature.state.al.us/files/pdf/SearchableInstruments/2024RS/HB172-enr.pdf|Deceptive election media: disclosure and remedies in the enrolled measure.|Enactment cross-checked against NCSL; enrolled text alone is not proof of signature.
AK|Alaska|institutional|HB53 / ch. 10 SLA 2025|public|enacted|mixed|https://www.akleg.gov/basis/Committee/Details/34?code=HHB53|Budget legislation includes state AI planning and project provisions.|Official history confirms enactment; AI scope is identified by NCSL. Spending and delivery were not audited.
AZ|Arizona|sectoral|HB2175 / ch. 165 (2025)|health|enacted|primary|https://www.azleg.gov/legtext/57leg/1r/laws/0165.htm|Medical-necessity denials require independent medical-director review rather than sole reliance on recommendations.|A technology-neutral insurance safeguard; applies from July 1, 2026. Not a general AI law.
AR|Arkansas|targeted|HB1876 / Act 927 (2025)|media|enacted|primary|https://www.arkleg.state.ar.us/Acts/FTPDocument?ddBienniumSession=2025%2F2025R&file=927.pdf&path=%2FACTS%2F2025R%2FPublic%2F|Allocates specified ownership interests associated with AI output and training, including employment circumstances.|State-law allocation does not establish federal copyright eligibility or eliminate existing rights.
CA|California|lifecycle|SB53 / ch. 138 (2025); SB243 / ch. 677 (2025)|frontier,interaction|enacted|primary|https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260SB53|Frontier-model risk frameworks and incident reporting; a separate companion-chatbot law addresses disclosure and user safeguards.|Different laws, covered entities and thresholds. An official reporting portal is an implementation artifact, not demonstrated risk reduction.
CO|Colorado|lifecycle|SB26-189 (2026)|decisions|enacted|primary|https://leg.colorado.gov/bills/sb26-189|The replacement automated-decision framework assigns documentation, notice, correction and meaningful human-review duties.|Core requirements begin January 1, 2027. The earlier SB24-205 regime is not the current implementation baseline.
CT|Connecticut|institutional|PA23-16 / §4a-2e|public|enacted|primary|https://www.cga.ct.gov/current/pub/chap_057.htm#sec_4a-2e|Annual state-agency AI inventory and ongoing assessment duties.|This entry assesses the 2023 public-sector mechanism. The complete effect of PA26-15 is outside this edition's assessed corpus.
DE|Delaware|institutional|HB333 (2024)|public|enacted|primary|https://legis.delaware.gov/BillDetail?LegislationId=140866|Creates an AI commission with inventory and recommendation responsibilities.|A legislative institution is not proof that private-sector controls or recommendations have been implemented.
FL|Florida|targeted|HB919 / ch. 2024-126|media|enacted|primary|https://www.flsenate.gov/Session/Bill/2024/919|Requires disclaimers for covered political advertising using generated media.|Election-specific scope and statutory intent conditions; effective July 1, 2024.
GA|Georgia|sectoral|SB540 (2026)|interaction|enacted|primary|https://senatepress.net/majority-leader-jason-anavitarte-applauds-signing-of-sb-540-to-protect-children-online.html|Signed legislation addresses conversational AI interactions with minors and crisis-resource access.|Official Senate signing account supports this narrow description; provision-level effective dates were not independently resolved here.
HI|Hawaii|targeted|HRS §11-303 / Act 191 (2024)|media|enacted|primary|https://data.capitol.hawaii.gov/hrscurrent/Vol01_Ch0001-0042F/HRS0011/HRS_0011-0303.htm|Addresses materially deceptive campaign media with disclosure exceptions.|Election-period and media-format conditions matter; not a general synthetic-content prohibition.
ID|Idaho|targeted|HB664 / ch. 172 (2024)|media|enacted|secondary|https://legiscan.com/ID/supplement/H0664/id/442216|The FAIR Elections Act addresses deceptive generated election media.|Secondary-source verification only: the legislature's website was inaccessible to this review. Not included in primary-only comparisons.
IL|Illinois|sectoral|HB3773 / PA103-0804|employment|enacted|primary|https://www.ilga.gov/Legislation/publicacts/view/103-0804|Extends employment civil-rights protections to discriminatory AI use and requires notice.|Effective January 1, 2026. Rulemaking and employer compliance were not audited.
IN|Indiana|institutional|SEA150 / PL108-2024|public|enacted|primary|https://www.in.gov/dor/files/2024-legislative-synopsis.pdf|Creates public AI governance arrangements, including standards for voluntary public-entity inventories.|The inventory submission provision is permissive. Its July 1, 2025 start does not make all inventories mandatory.
IA|Iowa|targeted|HF2240 / ch. 1065 (2024)|media|enacted|primary|https://www.legis.iowa.gov/legislation/billTracking/billHistory?billName=HF+2240&ga=90|Addresses dissemination of altered explicit depictions as harassment.|A targeted likeness safeguard; not a general model-development or deployment framework.
KS|Kansas|targeted|SB186 (2025)|media|enacted|primary|https://www.governor.ks.gov/Home/Components/News/News/648/56|Signed legislation addresses AI-generated sexual depictions and related privacy harms.|Offense-specific scope; enactment does not establish implementation or enforcement outcomes.
KY|Kentucky|targeted|HB207 / Act 15 (2024)|media|enacted|primary|https://apps.legislature.ky.gov/law/acts/24RS/documents/0015.pdf|Extends protections concerning sexual depictions of minors to specified computer-generated material.|This selected criminal-law anchor does not represent Kentucky's full privacy or AI portfolio.
LA|Louisiana|targeted|RS14:73.14|media|enacted|primary|https://legis.la.gov/Legis/Law.aspx?d=1388452|Addresses nonconsensual AI-generated nude images.|The selected offense has particular knowledge, consent and depiction elements; no general AI maturity score is inferred.
ME|Maine|sectoral|10 MRSA §1500-DD / PL2025 c. 294|interaction|enacted|primary|https://legislature.maine.gov/legis/statutes/10/title10sec1500-DD.html|Requires disclosures for consumer-facing chatbots where users could be misled into believing they are interacting with a human.|A consumer transparency mechanism, not a general audit or risk-management obligation.
MD|Maryland|institutional|SB818 / ch. 496 (2024)|public|enacted|primary|https://mgaleg.maryland.gov/2024RS/chapters_noln/Ch_496_sb0818E.pdf|Directs public-sector AI inventories, policies and assessment arrangements.|Applies to state governance; this record does not characterize Maryland's separate consumer privacy regime.
MA|Massachusetts|targeted|2024 intimate-image legislation|media|enacted|primary|https://www.mass.gov/news/governor-healey-signs-bill-banning-revenge-porn-expanding-protections-against-abuse-and-exploitation|Extends protections against image-based abuse; state guidance addresses student deepfake incidents.|The selected legislation and 2026 school guidance are distinct evidence objects; guidance is not evidence of universal school compliance.
MI|Michigan|targeted|MCL168.932f|media|enacted|primary|https://www.michigan.gov/ag/consumer-protection/election-protection-2026/protecting-michigan-voters-from-ai-generated-election-misinformation|Regulates specified deceptive election media, as explained in the Attorney General's 2026 voter-protection guidance.|Campaign context, timing and statutory exceptions limit applicability.
MN|Minnesota|rights|§325M.14, Consumer Data Privacy Act|decisions|enacted|primary|https://www.revisor.mn.gov/statutes/cite/325M.14|Provides covered consumers with profiling-related rights, including information and review-related protections.|Consumer privacy thresholds and exemptions apply. This is not a universal right governing every AI decision.
MS|Mississippi|targeted|SB2577 (2024)|media|enacted|primary|https://www.legislature.ms.gov/media/1352/senate_summary_final_2024_v3.pdf|Addresses deceptive election digitizations within a specified pre-election window.|Effective July 1, 2024; this entry uses the legislature's enacted-bill summary.
MO|Missouri|unclassified|SB1324 (2026), proposal|interaction|proposal|primary|https://www.senate.mo.gov/BillTracking/Bills/BillInformation?BillID=307&year=2026|The official record shows a committee do-pass status for an AI online-content proposal.|No enactment is established for this instrument. The displayed prospective effective date is not evidence that it became law.
MT|Montana|lifecycle|SB212 (2025), Right to Compute Act|infrastructure|enacted|primary|https://docs.legmt.gov/download-ticket?ticketId=ab38ae4c-551c-4b8c-bd8f-1226b2d67085|Combines computing protections with risk-management provisions for AI controlling critical infrastructure.|Narrow infrastructure trigger. The final law should not be described as containing the proposal's discarded shutdown requirement.
NE|Nebraska|rights|§87-1116 / LB1074 (2024)|decisions|enacted|primary|https://nebraskalegislature.gov/laws/statutes.php?statute=87-1116|Requires data-protection assessments for covered high-risk processing, including specified profiling.|A consumer privacy mechanism with thresholds and exemptions, not an AI-only statute.
NV|Nevada|sectoral|NRS629.610 / AB406 (2025)|health|enacted|primary|https://www.leg.state.nv.us/nrs/nrs-629.html|Restricts licensed mental- and behavioral-health providers' use of AI to deliver direct care, with administrative exceptions.|A professional-care boundary; does not prohibit every AI use in health services.
NH|New Hampshire|institutional|HB1688 / ch. 209 (2024)|public|enacted|primary|https://gc.nh.gov/bill_status/legacy/bs2016/billText.aspx?id=1597&sy=2024&txtFormat=pdf&v=current|Addresses state-government AI use, transparency and human oversight.|Public-sector scope; it should not be presented as a private-sector omnibus regime.
NJ|New Jersey|targeted|PL2025 c. 40 / A3540|media|enacted|primary|https://pub.njleg.state.nj.us/Bills/2024/AL25/40_.HTM|Creates targeted civil and criminal protections involving deceptive generated media.|Specific injury, conduct and intent elements matter; publication of synthetic media is not uniformly unlawful.
NM|New Mexico|targeted|HB182 / ch. 57 (2024)|media|enacted|primary|https://www.sos.nm.gov/2024/03/06/secretary-of-state-responds-to-priority-election-bills-becoming-law/|Adds campaign disclosure requirements for covered AI-generated media.|Election safeguards do not establish general AI-provider accountability duties.
NY|New York|lifecycle|S6953B / ch. 699 (2025), amended by S8828 / ch. 96 (2026)|frontier|enacted|primary|https://www.nysenate.gov/legislation/bills/2025/S8828|The amended RAISE framework addresses frontier-model safety and regulatory accountability.|Effective January 1, 2027. The 2026 amendment controls this edition's date treatment.
NC|North Carolina|targeted|GS14-190.5A, as amended in 2024|media|enacted|primary|https://dashboard.ncleg.gov/api/Services/BillSummary/2025/H934-SMTQ-35%28e1%29-v-2|Existing law covers specified AI-generated private images and sexual-exploitation material.|The cited legislative analysis describes existing law separately from H934's proposed changes; only its current-law discussion supports this entry.
ND|North Dakota|targeted|HB1167 (2025)|media|enacted|primary|https://ndlegis.gov/assembly/69-2025/regular/bill-overview/bo1167.html?search=artificial+i|Requires identification of covered AI impersonation in political communications.|Campaign-specific trigger. Routine text assistance should not be conflated with covered impersonation.
OH|Ohio|institutional|ORC3301.24 / HB96 (2025)|public|enacted|primary|https://codes.ohio.gov/ohio-revised-code/section-3301.24|Requires a state model AI policy and school-system adoption of AI-use policies by July 1, 2026.|The model policy is publicly available; local adoption and policy effectiveness were not audited.
OK|Oklahoma|targeted|HB1364 (2025)|media|enacted|primary|https://www.okhouse.gov/posts/news-20250507_4|Signed legislation extends protections against nonconsensual intimate imagery to AI-generated material.|Targeted criminal-law protection; not evidence of a comprehensive AI accountability system.
OR|Oregon|sectoral|ORS678.027 (2025 edition)|health|enacted|primary|https://www.oregonlegislature.gov/bills_laws/ors/ors678.html|Restricts nonhuman AI use of protected nursing titles.|A professional-title rule. The cited code edition does not incorporate all 2026 session changes.
PA|Pennsylvania|targeted|18 PaCS §6312 / Act 125 (2024)|media|enacted|primary|https://www.legis.state.pa.us/WU01/LI/LI/CT/HTM/18/00.063.012.000..HTM|Updates child-sexual-abuse depiction provisions to address specified synthetic material.|The selected criminal statute is not a full account of state AI legislation or administrative use.
RI|Rhode Island|rights|§6-48.1-7, Data Transparency and Privacy Protection Act|decisions|enacted|primary|https://webserver.rilegislature.gov/Statutes/TITLE6/6-48.1/6-48.1-7.htm|Requires assessments for covered high-risk processing, including specified profiling.|Effective January 1, 2026; consumer-data scope and exemptions apply.
SC|South Carolina|targeted|H3058 (2025)|media|enacted|primary|https://www.governor.sc.gov/news/2025-05/gov-henry-mcmaster-signs-unauthorized-disclosure-intimate-images-bill-law|Signed legislation addresses unauthorized intimate-image disclosure, including AI-generated depictions.|May 12, 2025 signature and May 29 ceremonial event are distinct dates.
SD|South Dakota|targeted|SB79 (2024)|media|enacted|primary|https://sdlegislature.gov/Session/Bill/24991|Extends child-sexual-abuse material definitions to specified AI-generated depictions.|Depiction and offense elements constrain scope; not a general ban on generative AI.
TN|Tennessee|targeted|ELVIS Act (2024)|media|enacted|primary|https://www.tn.gov/governor/news/2024/4/25/gov--lee-marks-the-close-of-the-2024-legislative-session.html|Protects voice and likeness interests against specified AI-related misuse.|Publicity and likeness rights operate differently from model-safety regulation.
TX|Texas|lifecycle|HB149 (2025), TRAIGA|decisions,interaction,public|enacted|primary|https://capitol.texas.gov/tlodocs/89R/billtext/html/HB00149F.htm|Sets prohibited uses, specified disclosure duties and an enforcement and sandbox structure.|Effective January 1, 2026. The enacted discrimination standard is intentional conduct, not a general disparate-impact test.
UT|Utah|institutional|AI Policy Act and subsequent amendments|interaction,health,public|enacted|primary|https://commerce.utah.gov/ai/ai-faq/|An AI policy office and regulatory-mitigation program coexist with disclosure and mental-health chatbot safeguards.|The office describes a bounded prescription-renewal pilot. Agency-reported operation is not independent validation of clinical safety.
VT|Vermont|institutional|3 VSA §5022 / Act 132 (2022)|public|enacted|primary|https://legislature.vermont.gov/statutes/section/03/069/05022|Assigns public AI review, inventory and reporting responsibilities to a state division.|Institutional duties are assessed here; performance of every mandated review is not established.
VA|Virginia|rights|§59.1-577, Consumer Data Protection Act|decisions|enacted|primary|https://law.lis.virginia.gov/vacode/title59.1/chapter53/section59.1-577/|Gives covered consumers profiling opt-out rights and an appeal process for rights requests.|Consumer privacy coverage and exemptions apply; this is not an omnibus AI-specific assessment.
WA|Washington|sectoral|ESHB2225 / ch. 168 (2026)|interaction|enacted|primary|https://app.leg.wa.gov/billsummary?BillNumber=2225&Initiative=false&Year=2026|Enacts a companion-chatbot regulatory framework.|Signed March 24, 2026; effective January 1, 2027. Enacted and effective are visibly separated in this atlas.
WV|West Virginia|institutional|§5A-6-9 / HB3187 (2025)|public|enacted|primary|https://code.wvlegislature.gov/5A-6-9/|Establishes a state AI task force and governance responsibilities.|This institutional anchor does not imply that every recommendation has become a binding rule.
WI|Wisconsin|targeted|2023 Wisconsin Act 123|media|enacted|primary|https://ethics.wi.gov/Resources/Candidate%20Overview%20Webinar%202024%20Slides.pdf|Requires AI disclosures in covered political advertising.|Official Ethics Commission implementation material; effective March 23, 2024. The review does not assess enforcement outcomes.
WY|Wyoming|targeted|HB0102 / ch. 91 (2026)|media|enacted|primary|https://www.wyoleg.gov/2026/Summaries/HB0102.pdf|Addresses AI-enabled harms involving minors, with specified criminal and developer-liability provisions.|Effective July 1, 2026. Particular knowledge and intent conditions matter.
DC|District of Columbia|unclassified|No anchor classified in this edition|none|unassessed|none|https://dccouncil.gov/legislation/|Included separately from the 50 states; legislative classification remains unassessed.|This is a research gap, not a finding that the District has no applicable law.'''
states=[]
for line in raw.splitlines():
    code,name,pathway,instrument,domains,status,source_type,url,claim,boundary=line.split('|')
    states.append(dict(code=code,name=name,pathway=pathway,instrument=instrument,domains=[] if domains=='none' else domains.split(','),status=status,source_type=source_type,source_url=url,claim=claim,boundary=boundary,observed_at='2026-09-14',implementation='not assessed',secondary_url=None))
extra={
 'CA': [('SB243 companion-chatbot law','https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260SB243'),('Cal OES reporting surface','https://www.caloes.ca.gov/office-of-the-director/operations/homeland-security/california-cybersecurity-integration-center/transparency-in-frontier-ai-act-reporting/')],
 'CT':[('Published 2023 inventory','https://portal.ct.gov/das/-/media/das-beta/pdf/legislative-testimony/presentation-and-reports/2023-state-of-connecticut-executive-branch-artificial-intelligence-inventory.pdf')],
 'OH':[('Department model policy','https://education.ohio.gov/Topics/AI-in-Ohio-s-Education/Model-Policy')],
 'UT':[('Office of AI Policy','https://commerce.utah.gov/ai/')],
 'MA':[('2026 school deepfake guidance','https://www.mass.gov/news/governor-healey-provides-guidance-to-schools-to-investigate-deepfake-images-and-videos-to-protect-students')],
 'IA':[('Education department enacted-law summary','https://educate.iowa.gov/media/10356/download')],
 'AL':[('NCSL enactment cross-check','https://www.ncsl.org/technology-and-communication/artificial-intelligence-2024-legislation')],
 'AK':[('NCSL budget scope cross-check','https://www.ncsl.org/technology-and-communication/artificial-intelligence-2025-legislation/ftag')]
}
for s in states:
    s['additional_sources']=[dict(title=t,url=u) for t,u in extra.get(s['code'],[])]
    if s['code'] in ['CA','CT','OH','MA','WI']: s['implementation']='public artifact observed; effectiveness not assessed'
    if s['code']=='UT': s['implementation']='agency reports bounded program operation; outcomes not independently assessed'
    if s['code'] in ['AL','AK']: s['secondary_url']=s['additional_sources'][0]['url']
doc={'title':'Beyond the bill count: State AI legislative maturity atlas','edition':'1.0','as_of':'2026-09-14','scope':'Representative legislative anchors across all 50 states; District of Columbia separate. Not an exhaustive legal inventory or state ranking. Empty domain cells mean not assessed in the selected corpus.','states':states}
(ROOT/'data/states.json').write_text(json.dumps(doc,indent=2,ensure_ascii=False)+'\n')
fields=['code','name','pathway','instrument','domains','status','source_type','source_url','claim','boundary','observed_at','implementation','secondary_url','additional_sources']
with (ROOT/'data/states.csv').open('w',newline='') as f:
    w=csv.DictWriter(f,fieldnames=fields,lineterminator="\n");w.writeheader()
    for s in states: w.writerow({**s,'domains':'; '.join(s['domains']),'additional_sources':'; '.join(x['title']+': '+x['url'] for x in s['additional_sources'])})
assert len(states)==51 and len({s['code'] for s in states})==51
print('Wrote 50 states + DC; representative instrument ledger.')
